# compose/Dockerfile.web

# 1. Базовый образ с Python
FROM python:3.11-slim

# 2. Установим системные зависимости (нужны для сборки некоторых Python-библиотек)
RUN apt-get update && apt-get install -y gcc python3-dev git

# 3. Создаем рабочую директорию внутри контейнера
WORKDIR /app

# 4. Копируем файлы проекта в контейнер
COPY . /app/

# 5. Устанавливаем зависимости Python
RUN pip install --upgrade pip \
    && pip install -r requirements.txt \
    && pip install psycopg2-binary

# 6. Собираем статические файлы Django (для админки)
RUN mkdir -p /app/staticfiles && \
    # 1) Импортируем модуль os в начало файла settings.py
    sed -i '1i import os' /app/knaz_tg_bot_calend/settings.py && \
    # 2) Добавляем определение STATIC_ROOT после строки с STATIC_URL
    sed -i '/STATIC_URL =/a\STATIC_ROOT = os.path.join(BASE_DIR, \"staticfiles\")' /app/knaz_tg_bot_calend/settings.py && \
    python manage.py collectstatic --noinput --clear --settings=knaz_tg_bot_calend.settings
# 7. Указываем команду для запуска контейнера
CMD ["gunicorn", "knaz_tg_bot_calend.wsgi:application", "--bind", "0.0.0.0:8000"]