# Generated by Django 5.2.14 on 2026-05-09 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botstatistics',
            options={'ordering': ['-date'], 'verbose_name': 'Статистика бота', 'verbose_name_plural': 'Статистика бота'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата встречи')),
                ('time', models.TimeField(verbose_name='Время встречи')),
                ('details', models.TextField(blank=True, verbose_name='Детали встречи')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.event', verbose_name='Событие')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
                ('participants', models.ManyToManyField(related_name='participating_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ['date', 'time'],
            },
        ),
    ]
