# Generated by Django 5.2.14 on 2026-05-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_botstatistics_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
    ]
